[package]
name = "leetcode-rust"
version = "0.1.0"
edition = "2021"
authors = ["webytes <webytes@qq.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
